apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-worker
  labels:
    app: fraud-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fraud-worker
  template:
    metadata:
      labels:
        app: fraud-worker
    spec:
      containers:
      - name: fraud-worker
        image: 802104113126.dkr.ecr.ap-south-1.amazonaws.com/fraud-worker:e23dd89f1b024bf7fdf924807ef6100c9a9d39dd
        env:
        - name: AWS_REGION
          value: "ap-south-1"
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"