apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion-api
  labels:
    app: ingestion-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ingestion-api
  template:
    metadata:
      labels:
        app: ingestion-api
    spec:
      containers:
      - name: ingestion-api
        image: 802104113126.dkr.ecr.ap-south-1.amazonaws.com/ingestion-api:e23dd89f1b024bf7fdf924807ef6100c9a9d39dd
        ports:
        - containerPort: 5001
        env:
        - name: PORT
          value: "5001"
        - name: AWS_REGION
          value: "ap-south-1"
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"