name: Build and Push Docker Images to ECR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-ingestion-api:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Run Tests for Ingestion API
      run: |
        cd ingestion-api
        npm install
        npm test

  build-and-push:
    needs: test-ingestion-api
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build and push Ingestion API
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ingestion-api
        IMAGE_TAG: ${{ github.sha }}
      run: |
        cd ingestion-api
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Build and push Fraud Worker
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: fraud-worker
        IMAGE_TAG: ${{ github.sha }}
      run: |
        cd fraud-worker
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Update Kubernetes manifests
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        sed -i -E "s|(image: .*/ingestion-api):.*|\1:$IMAGE_TAG|g" k8s/ingestion-api-deployment.yaml
        sed -i -E "s|(image: .*/fraud-worker):.*|\1:$IMAGE_TAG|g" k8s/fraud-worker-deployment.yaml
        
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
       
        git pull origin main --rebase
        
        git add k8s/
        git commit -m "Update image tags to $IMAGE_TAG for ArgoCD [skip ci]" || echo "No changes to commit"
        
        git push origin main

  deploy-frontend-to-s3:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies and Build (Vite)
      env:
        VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
      run: |
        cd frontend
        npm install
        npm run build

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Deploy Frontend to S3 Bucket
      run: |
        aws s3 sync ./frontend/dist/ s3://fintech-k8s-frontend-802104113126 --delete

    - name: Invalidate CloudFront Cache
      run: |
        aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DIST_ID }} --paths "/*"